insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (1, 'Shane', 1, 'O+', 'divorced', '786-281-7551', 'PO Box 44341', 24);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (2, 'Otha', 0, 'A+', 'widowed', '376-460-5082', 'PO Box 2838', 38);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (3, 'Iggy', 1, 'B+', 'widowed', '112-684-2690', 'PO Box 85471', 52);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (4, 'Corrie', 1, 'A-', 'widowed', '649-456-9897', 'Room 425', 25);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (5, 'Vassili', 1, 'B+', 'single', '153-269-5578', 'Room 1372', 58);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (6, 'Denyse', 1, 'O+', 'widowed', '178-336-3584', 'Apt 845', 20);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (7, 'Carmela', 0, 'B-', 'widowed', '827-542-3293', 'Apt 1510', 41);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (8, 'Gale', 1, 'B+', 'single', '174-398-6849', '17th Floor', 29);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (9, 'Oralee', 0, 'B+', 'divorced', '430-879-7846', 'Room 800', 32);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (10, 'Kailey', 1, 'O+', 'divorced', '616-246-1172', 'Suite 16', 28);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (11, 'Bran', 0, 'B-', 'single', '853-440-9372', 'Room 823', 32);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (12, 'Sue', 0, 'O-', 'single', '948-654-3672', '10th Floor', 36);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (13, 'Gillie', 0, 'O-', 'single', '313-662-1568', 'Room 1972', 54);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (14, 'Margarita', 1, 'B+', 'single', '872-409-7274', 'Apt 737', 13);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (15, 'Alister', 1, 'B-', 'divorced', '843-822-5085', 'Suite 44', 40);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (16, 'Merna', 1, 'O+', 'single', '656-818-6843', 'Room 1079', 12);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (17, 'Zed', 1, 'A-', 'single', '952-516-3142', 'PO Box 14874', 60);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (18, 'Bill', 1, 'B+', 'married', '747-585-8742', 'Room 1311', 27);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (19, 'Inga', 1, 'O-', 'widowed', '145-259-6372', 'Suite 93', 55);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (20, 'Tani', 0, 'O+', 'widowed', '251-628-6744', 'PO Box 43156', 61);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (21, 'Orlando', 1, 'A-', 'single', '304-563-0523', 'Apt 128', 38);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (22, 'Elayne', 1, 'A-', 'single', '678-360-2527', 'PO Box 18406', 48);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (23, 'Kerr', 0, 'B+', 'divorced', '245-583-8521', 'Suite 47', 56);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (24, 'Gearalt', 0, 'B+', 'widowed', '681-792-3341', 'PO Box 47473', 61);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (25, 'Quincey', 1, 'A+', 'single', '383-255-0867', 'Room 1943', 34);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (26, 'Fina', 0, 'A-', 'single', '653-762-5566', '13th Floor', 68);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (27, 'Stanislaw', 1, 'A+', 'widowed', '881-289-1902', 'PO Box 51065', 35);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (28, 'Chiarra', 0, 'A+', 'divorced', '155-349-0025', '16th Floor', 11);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (29, 'Velvet', 1, 'A+', 'divorced', '550-736-3706', 'Apt 1609', 47);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (30, 'Octavia', 0, 'A+', 'married', '152-551-2570', 'Apt 77', 45);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (31, 'Else', 0, 'O+', 'single', '229-927-0730', 'Apt 1834', 33);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (32, 'Berti', 0, 'O+', 'married', '905-425-9893', 'Suite 75', 65);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (33, 'Celine', 0, 'A+', 'divorced', '617-162-9600', 'Apt 1690', 53);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (34, 'Ruthy', 1, 'A+', 'married', '161-361-9906', 'Room 1413', 43);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (35, 'Stacey', 1, 'O+', 'married', '547-319-6217', '11th Floor', 24);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (36, 'Doyle', 1, 'B-', 'divorced', '515-365-8169', 'Room 1062', 16);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (37, 'Beltran', 1, 'A+', 'widowed', '470-536-5503', 'Suite 86', 11);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (38, 'Jamal', 0, 'A+', 'divorced', '219-737-0725', 'Apt 197', 60);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (39, 'Levi', 1, 'A+', 'widowed', '743-188-3872', 'Apt 1415', 47);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (40, 'Lorri', 1, 'A-', 'married', '537-237-7520', 'Room 491', 70);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (41, 'Cad', 1, 'A-', 'divorced', '377-628-9569', '19th Floor', 52);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (42, 'Quinlan', 1, 'B+', 'single', '796-334-7432', 'PO Box 23215', 18);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (43, 'Sibyl', 0, 'A-', 'divorced', '630-579-9758', '1st Floor', 28);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (44, 'Lonnie', 0, 'A-', 'divorced', '940-752-4658', 'Apt 574', 69);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (45, 'Cyndy', 1, 'A-', 'widowed', '574-617-2829', '15th Floor', 28);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (46, 'Joycelin', 0, 'B-', 'single', '818-760-9273', '14th Floor', 37);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (47, 'Vasilis', 0, 'O-', 'married', '822-350-0188', 'PO Box 92249', 12);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (48, 'Spenser', 1, 'A+', 'single', '583-445-3231', 'Apt 823', 16);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (49, 'Tatiania', 1, 'B-', 'divorced', '202-918-6697', 'PO Box 29786', 40);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (50, 'Adela', 0, 'A+', 'divorced', '488-279-3061', 'Suite 16', 49);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (51, 'Lem', 1, 'A+', 'single', '254-687-6263', 'Room 1887', 28);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (52, 'Calv', 1, 'B+', 'single', '457-424-4551', 'Suite 99', 68);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (53, 'Kahaleel', 0, 'O-', 'married', '450-734-0637', 'PO Box 70235', 45);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (54, 'Illa', 1, 'O+', 'divorced', '401-924-8666', '14th Floor', 35);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (55, 'Karlie', 1, 'B-', 'single', '200-262-1504', 'PO Box 87960', 35);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (56, 'Sancho', 0, 'B-', 'single', '883-472-0748', '11th Floor', 57);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (57, 'Margarita', 1, 'A+', 'married', '424-353-3167', 'Room 1841', 62);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (58, 'Gypsy', 0, 'O-', 'divorced', '781-457-9680', 'Room 985', 65);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (59, 'Julietta', 0, 'A-', 'divorced', '400-272-4651', 'Suite 93', 46);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (60, 'Bancroft', 1, 'B-', 'married', '195-878-8502', '1st Floor', 44);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (61, 'Nappy', 1, 'O-', 'divorced', '724-544-4860', 'Room 977', 29);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (62, 'Laurette', 1, 'O+', 'divorced', '999-715-5296', 'Apt 1458', 43);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (63, 'Bobette', 0, 'B+', 'divorced', '330-496-6022', 'PO Box 14713', 40);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (64, 'Giles', 0, 'O-', 'divorced', '821-351-2698', 'Apt 1862', 66);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (65, 'Amandy', 0, 'A+', 'divorced', '433-476-1334', 'PO Box 56247', 24);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (66, 'Vidovik', 0, 'O-', 'single', '562-839-4197', 'PO Box 34768', 15);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (67, 'Torrie', 0, 'O-', 'single', '898-544-5069', 'PO Box 3569', 27);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (68, 'Hedwig', 1, 'B-', 'widowed', '104-353-3259', 'Room 1322', 24);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (69, 'Selia', 1, 'B+', 'single', '298-214-6073', 'Room 201', 70);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (70, 'Tades', 1, 'A-', 'divorced', '648-344-5050', '13th Floor', 27);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (71, 'Clarie', 0, 'A+', 'widowed', '284-479-7197', 'Suite 96', 42);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (72, 'Fidole', 0, 'A+', 'single', '644-781-1992', 'Suite 52', 34);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (73, 'Tallulah', 0, 'A+', 'divorced', '275-763-8233', 'Room 222', 53);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (74, 'Emory', 1, 'O-', 'single', '190-262-5273', 'Suite 18', 23);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (75, 'Winona', 1, 'B-', 'divorced', '201-248-2778', 'Apt 1521', 67);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (76, 'Peadar', 0, 'A+', 'widowed', '575-434-4301', 'Apt 570', 41);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (77, 'Klaus', 0, 'O+', 'widowed', '842-919-9747', 'Suite 28', 19);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (78, 'Mair', 1, 'O+', 'widowed', '554-535-8215', 'Suite 57', 59);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (79, 'Basile', 0, 'B-', 'single', '499-657-9714', 'Apt 976', 29);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (80, 'Alina', 1, 'B+', 'married', '840-516-7431', 'Room 1341', 66);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (81, 'Garfield', 0, 'A+', 'single', '303-575-9239', '10th Floor', 66);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (82, 'Rivkah', 1, 'A+', 'widowed', '571-482-8606', 'PO Box 8391', 57);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (83, 'Anabella', 0, 'O+', 'married', '629-201-2991', '18th Floor', 17);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (84, 'Shirleen', 0, 'O-', 'single', '259-150-7612', '10th Floor', 52);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (85, 'Pebrook', 1, 'A+', 'divorced', '773-531-3797', 'Apt 1128', 13);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (86, 'Randolph', 1, 'O-', 'single', '341-889-4542', 'PO Box 20066', 61);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (87, 'Giusto', 0, 'B-', 'widowed', '535-979-3518', 'Apt 162', 48);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (88, 'Fredrika', 1, 'A-', 'single', '500-760-2888', 'Suite 38', 51);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (89, 'Tildi', 1, 'O-', 'married', '329-699-8432', 'PO Box 8648', 26);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (90, 'Joanie', 1, 'B-', 'single', '344-738-1087', 'PO Box 3931', 43);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (91, 'Barris', 1, 'A+', 'divorced', '909-795-2410', 'Room 657', 65);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (92, 'Nollie', 0, 'A-', 'widowed', '885-390-6842', 'PO Box 61904', 59);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (93, 'Roanna', 0, 'O+', 'single', '731-439-9946', '6th Floor', 45);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (94, 'Tedmund', 0, 'B+', 'widowed', '358-272-4675', '10th Floor', 49);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (95, 'Natala', 0, 'O+', 'divorced', '863-270-3963', 'Apt 1254', 58);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (96, 'Eunice', 0, 'O-', 'married', '675-900-8082', 'Room 1343', 47);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (97, 'Aubry', 0, 'B+', 'divorced', '950-679-1848', 'Suite 84', 48);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (98, 'Nefen', 1, 'O+', 'married', '829-494-1890', '4th Floor', 32);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (99, 'Wells', 0, 'B+', 'widowed', '465-247-3270', 'Suite 66', 13);
insert into person (pid, name, gender, blood_group, marital_status, cnic_or_bcn, residential_address, age) values (100, 'Justen', 1, 'O+', 'divorced', '247-599-9910', 'PO Box 62314', 20);
