insert into project (pid, title, number, budget) values (1, 'Junior Executive', 1, 444);
insert into project (pid, title, number, budget) values (2, 'Administrative Assistant IV', 2, 497);
insert into project (pid, title, number, budget) values (3, 'Geologist I', 3, 301);
insert into project (pid, title, number, budget) values (4, 'Media Manager I', 4, 417);
insert into project (pid, title, number, budget) values (5, 'Recruiter', 5, 215);
insert into project (pid, title, number, budget) values (6, 'Account Executive', 6, 170);
insert into project (pid, title, number, budget) values (7, 'Engineer I', 7, 383);
insert into project (pid, title, number, budget) values (8, 'Financial Advisor', 8, 420);
insert into project (pid, title, number, budget) values (9, 'VP Sales', 9, 104);
insert into project (pid, title, number, budget) values (10, 'Staff Scientist', 10, 300);
insert into project (pid, title, number, budget) values (11, 'Registered Nurse', 11, 342);
insert into project (pid, title, number, budget) values (12, 'Software Test Engineer III', 12, 397);
insert into project (pid, title, number, budget) values (13, 'Database Administrator III', 13, 142);
insert into project (pid, title, number, budget) values (14, 'Payment Adjustment Coordinator', 14, 166);
insert into project (pid, title, number, budget) values (15, 'Editor', 15, 129);
insert into project (pid, title, number, budget) values (16, 'Sales Representative', 16, 234);
insert into project (pid, title, number, budget) values (17, 'Automation Specialist IV', 17, 290);
insert into project (pid, title, number, budget) values (18, 'Mechanical Systems Engineer', 18, 330);
insert into project (pid, title, number, budget) values (19, 'Nurse Practicioner', 19, 475);
insert into project (pid, title, number, budget) values (20, 'Product Engineer', 20, 208);
insert into project (pid, title, number, budget) values (21, 'Media Manager IV', 21, 365);
insert into project (pid, title, number, budget) values (22, 'Registered Nurse', 22, 309);
insert into project (pid, title, number, budget) values (23, 'Staff Scientist', 23, 210);
insert into project (pid, title, number, budget) values (24, 'Safety Technician IV', 24, 170);
insert into project (pid, title, number, budget) values (25, 'Programmer Analyst II', 25, 480);
insert into project (pid, title, number, budget) values (26, 'Safety Technician III', 26, 486);
insert into project (pid, title, number, budget) values (27, 'Cost Accountant', 27, 178);
insert into project (pid, title, number, budget) values (28, 'Business Systems Development Analyst', 28, 161);
insert into project (pid, title, number, budget) values (29, 'Tax Accountant', 29, 266);
insert into project (pid, title, number, budget) values (30, 'Marketing Assistant', 30, 367);
insert into project (pid, title, number, budget) values (31, 'Budget/Accounting Analyst II', 31, 284);
insert into project (pid, title, number, budget) values (32, 'Programmer III', 32, 173);
insert into project (pid, title, number, budget) values (33, 'Assistant Manager', 33, 251);
insert into project (pid, title, number, budget) values (34, 'Account Coordinator', 34, 116);
insert into project (pid, title, number, budget) values (35, 'Assistant Manager', 35, 392);
insert into project (pid, title, number, budget) values (36, 'Budget/Accounting Analyst IV', 36, 224);
insert into project (pid, title, number, budget) values (37, 'Pharmacist', 37, 326);
insert into project (pid, title, number, budget) values (38, 'Associate Professor', 38, 288);
insert into project (pid, title, number, budget) values (39, 'Senior Developer', 39, 296);
insert into project (pid, title, number, budget) values (40, 'General Manager', 40, 140);
insert into project (pid, title, number, budget) values (41, 'Sales Associate', 41, 116);
insert into project (pid, title, number, budget) values (42, 'Speech Pathologist', 42, 126);
insert into project (pid, title, number, budget) values (43, 'Data Coordiator', 43, 432);
insert into project (pid, title, number, budget) values (44, 'Help Desk Operator', 44, 219);
insert into project (pid, title, number, budget) values (45, 'VP Quality Control', 45, 497);
insert into project (pid, title, number, budget) values (46, 'Teacher', 46, 215);
insert into project (pid, title, number, budget) values (47, 'Health Coach III', 47, 478);
insert into project (pid, title, number, budget) values (48, 'Environmental Tech', 48, 140);
insert into project (pid, title, number, budget) values (49, 'Environmental Tech', 49, 258);
insert into project (pid, title, number, budget) values (50, 'Accounting Assistant III', 50, 241);
insert into project (pid, title, number, budget) values (51, 'Business Systems Development Analyst', 51, 411);
insert into project (pid, title, number, budget) values (52, 'General Manager', 52, 119);
insert into project (pid, title, number, budget) values (53, 'Data Coordiator', 53, 126);
insert into project (pid, title, number, budget) values (54, 'VP Quality Control', 54, 303);
insert into project (pid, title, number, budget) values (55, 'Account Coordinator', 55, 343);
insert into project (pid, title, number, budget) values (56, 'Research Associate', 56, 401);
insert into project (pid, title, number, budget) values (57, 'Senior Quality Engineer', 57, 181);
insert into project (pid, title, number, budget) values (58, 'Teacher', 58, 405);
insert into project (pid, title, number, budget) values (59, 'Compensation Analyst', 59, 493);
insert into project (pid, title, number, budget) values (60, 'Tax Accountant', 60, 119);
insert into project (pid, title, number, budget) values (61, 'Programmer IV', 61, 351);
insert into project (pid, title, number, budget) values (62, 'Senior Sales Associate', 62, 228);
insert into project (pid, title, number, budget) values (63, 'Programmer IV', 63, 349);
insert into project (pid, title, number, budget) values (64, 'Administrative Assistant I', 64, 190);
insert into project (pid, title, number, budget) values (65, 'Administrative Assistant IV', 65, 193);
insert into project (pid, title, number, budget) values (66, 'VP Accounting', 66, 479);
insert into project (pid, title, number, budget) values (67, 'Senior Developer', 67, 267);
insert into project (pid, title, number, budget) values (68, 'Human Resources Assistant II', 68, 411);
insert into project (pid, title, number, budget) values (69, 'Mechanical Systems Engineer', 69, 376);
insert into project (pid, title, number, budget) values (70, 'Media Manager I', 70, 241);
insert into project (pid, title, number, budget) values (71, 'Budget/Accounting Analyst II', 71, 147);
insert into project (pid, title, number, budget) values (72, 'Senior Editor', 72, 260);
insert into project (pid, title, number, budget) values (73, 'Operator', 73, 198);
insert into project (pid, title, number, budget) values (74, 'Librarian', 74, 377);
insert into project (pid, title, number, budget) values (75, 'Computer Systems Analyst IV', 75, 182);
insert into project (pid, title, number, budget) values (76, 'Information Systems Manager', 76, 102);
insert into project (pid, title, number, budget) values (77, 'Business Systems Development Analyst', 77, 246);
insert into project (pid, title, number, budget) values (78, 'Software Consultant', 78, 318);
insert into project (pid, title, number, budget) values (79, 'Professor', 79, 112);
insert into project (pid, title, number, budget) values (80, 'Legal Assistant', 80, 408);
insert into project (pid, title, number, budget) values (81, 'Senior Financial Analyst', 81, 408);
insert into project (pid, title, number, budget) values (82, 'Cost Accountant', 82, 387);
insert into project (pid, title, number, budget) values (83, 'Junior Executive', 83, 356);
insert into project (pid, title, number, budget) values (84, 'Food Chemist', 84, 408);
insert into project (pid, title, number, budget) values (85, 'Payment Adjustment Coordinator', 85, 305);
insert into project (pid, title, number, budget) values (86, 'Payment Adjustment Coordinator', 86, 219);
insert into project (pid, title, number, budget) values (87, 'Recruiting Manager', 87, 251);
insert into project (pid, title, number, budget) values (88, 'Senior Quality Engineer', 88, 237);
insert into project (pid, title, number, budget) values (89, 'Software Test Engineer I', 89, 350);
insert into project (pid, title, number, budget) values (90, 'Project Manager', 90, 391);
insert into project (pid, title, number, budget) values (91, 'General Manager', 91, 290);
insert into project (pid, title, number, budget) values (92, 'Junior Executive', 92, 200);
insert into project (pid, title, number, budget) values (93, 'Programmer Analyst I', 93, 394);
insert into project (pid, title, number, budget) values (94, 'Account Coordinator', 94, 371);
insert into project (pid, title, number, budget) values (95, 'Social Worker', 95, 233);
insert into project (pid, title, number, budget) values (96, 'VP Accounting', 96, 304);
insert into project (pid, title, number, budget) values (97, 'Web Developer I', 97, 489);
insert into project (pid, title, number, budget) values (98, 'VP Product Management', 98, 110);
insert into project (pid, title, number, budget) values (99, 'Senior Quality Engineer', 99, 172);
insert into project (pid, title, number, budget) values (100, 'Electrical Engineer', 100, 298);
